name: CI/CD
on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
    - name: CI/CD
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
        tox
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: First interaction
      uses: actions/first-interaction@v1.1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          # Thanks for the `issue`! 
          
          If this is a bug report, please include relevant logs to help us debug the problem.
          
          We look forward to resolving it very soon!
        pr-message: | 
          This is your `first` PR! You shoud be extremely proud!! This is definitely the first of many. Thanks a lot for your contribution!
          
          We look forward to reviewing your code :)
